CREATE TABLE IF NOT EXISTS users(
id SERIAL PRIMARY KEY,
firstName   VARCHAR(100),
lastName  VARCHAR(100),
username  VARCHAR(100),
password VARCHAR(100),
email   VARCHAR(100),
mobile  VARCHAR(100),
countryCode    VARCHAR(100),
address       VARCHAR(100),
lastLogin    TIMESTAMP,
verified     BOOLEAN,
active     BOOLEAN,
token       VARCHAR(100),
role         VARCHAR(100),
roleID       INT,
accountID    VARCHAR(100),
accountNumber    VARCHAR(100),
accountCurrency   VARCHAR(100),
accountStatus     VARCHAR(100),
dOB               VARCHAR(100),
city              VARCHAR(100),
state             VARCHAR(100),
country           VARCHAR(100),
taxIDType         VARCHAR(100),
taxID             VARCHAR(100),
fundingSource     VARCHAR(100),
employmentStatus   VARCHAR(100),
investingExperience   VARCHAR(100),
publicShareholder     VARCHAR(100),
anotherBrokerage      VARCHAR(100),
deviceID              VARCHAR(100),
profileCompletion     VARCHAR(100),
bIO                   VARCHAR(100),
facebookURL           VARCHAR(100),
twitterURL            VARCHAR(100),
instagramURL          VARCHAR(100),
publicPortfolio       VARCHAR(100),
employerName          VARCHAR(100),
occupation            VARCHAR(100),
unitApt               VARCHAR(100),
zipCode               VARCHAR(100),
stockSymbol           VARCHAR(100),
brokerageFirmName     VARCHAR(100),
brokerageFirmEmployeeName      VARCHAR(100),
brokerageFirmEmployeeRelationship VARCHAR(100),
shareholderCompanyName            VARCHAR(100),
avatar                            VARCHAR(100),
referredBy                        VARCHAR(100),
referralCode                      VARCHAR(100),
watchlistID                       VARCHAR(100),
perAccountLimit                   FLOAT,

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);