CREATE TABLE IF NOT EXISTS coinStatement(
ID SERIAL PRIMARY KEY,
userID      INTEGER,
coins  INTEGER,
type    VARCHAR(100),
reason   VARCHAR(100),
status BOOLEAN,

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);